# Generated by Django 2.2.8 on 2019-12-08 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('opsched', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationschedule',
            name='id',
        ),
        migrations.RemoveField(
            model_name='operationschedule',
            name='operation_name',
        ),
        migrations.AlterField(
            model_name='operationschedule',
            name='operation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
