# Generated by Django 2.2.8 on 2019-12-07 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opsched', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationschedule',
            name='op_finish_estimation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='operationschedule',
            name='op_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
