# Generated by Django 2.2.8 on 2019-12-07 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opsched', '0002_auto_20191207_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationschedule',
            old_name='op_finish_estimation_time',
            new_name='operation_finish_estimation_time',
        ),
        migrations.RenameField(
            model_name='operationschedule',
            old_name='op_start_time',
            new_name='operation_start_time',
        ),
    ]
