# Generated by Django 2.2.8 on 2019-12-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsched', '0003_auto_20191207_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationschedule',
            name='file_path',
            field=models.FilePathField(default='/', path='/Users/Kiichiro/djangogirls'),
            preserve_default=False,
        ),
    ]
